### ISSUE TITLE
toPNG

### ISSUE THREAD

**Issue by espohr** [simon123h/latex-image-paste#2]
Hi, 

I just tried to use your nice package. I found that I had to change toPng into toPNG in main.coffee, see below, to make it work on my macosx High Sierra machine with atom 1.29.

best regards
Eckhard

diff --git a/lib/main.coffee b/lib/main.coffee
index 4b09e83..4fd757e 100644
--- a/lib/main.coffee
+++ b/lib/main.coffee
@@ -44,7 +44,7 @@ module.exports = MarkdownImageAssistant =
     return if img.isEmpty()
     editor = atom.workspace.getActiveTextEditor()
     e.stopImmediatePropagation()
-    imgbuffer = img.toPng()
+    imgbuffer = img.toPNG()
     @process_file(editor, imgbuffer, ".png")

   # write a given buffer to the local "assets/" directory

**Comment by simon123h** [comment]
Thanks for reporting and providing a solution.
The issue should be fixed with commit a2bac97d5785ba8e09b3dc0c29efcd3b32f1cc74.
Feel free to reopen if the problem persists.
